import { createElement } from '@lwc/engine-dom';
import Lwc_0000_diaplayAccount from 'c/lwc_0000_diaplayAccount';

describe('c-lwc-0000-diaplay-account', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-0000-diaplay-account', {
            is: Lwc_0000_diaplayAccount
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});