name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Étape 1 : Récupérer le code source depuis le repo GitHub
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Installer Node.js pour exécuter les tests frontend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Étape 3 : Installer les dépendances Node du frontend (React/LWC)
      - name: Install frontend dependencies
        run: npm install

      # Étape 4 : Exécuter les tests Jest pour les composants LWC
      - name: Run LWC Jest tests
        run: npm run test:unit

      # Étape 5 : Installer Salesforce CLI et le plugin sfdx-git-delta pour les déploiements delta
      - name: Install SFDX CLI and sfdx-git-delta plugin
        run: |
          npm install -g @salesforce/cli@latest
          echo "y"
      #| npm install sfdx-git-delta@3.3.0 -g
      # sf plugins install sfdx-git-delta@v6.0.0
      - name: sf plugins install sfdx-git-delta@v6.0.0
        run: |
         sf plugins install sfdx-git-delta@v6.0.0
         echo "y"
         
      # Étape 6 : Authentification via JWT avec les identifiants secrets GitHub
      - name: Authentification Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SFDX_AUTH_URL}}
          SF_SECURITY_TOKEN : ${{ secrets.SECURITY_TOKEN }}
          SF_SERVER_KEY: ${{ secrets.SF_SERVER_KEY }}
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_CUSTOMER_SECRET: ${{ secrets.SF_CUSTOMER_SECRET }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_INSTANCE_URL: ${{secrets.INSTANCE_URL }}
          SF_ACCESS_TOKEN_CLI: ${{secrets.SF_ACCESS_TOKEN_CLI}}
        run: |
          echo "$SF_SERVER_KEY" > server.key
          sf org login jwt \
            --client-id $SF_CONSUMER_KEY \
            --jwt-key-file server.key \
            --username $SF_USERNAME \
            --alias cdcidev \
            --instance-url $SF_INSTANCE_URL

      # Étape 7 : Générer le delta de métadonnées (diff entre HEAD et origin/dev)
      - name: Generate metadata delta pull request
        run: |
          mkdir -p .temp
          sf sgd source delta --to HEAD --from origin/dev --output .temp

      # Étape 8 : Couverture des tests Apex
      - name: Run Apex Tests and Get Code Coverage
        run: |
          sf apex run test \
            --target-org cdcidev \
            --result-format human \
            --code-coverage \
            --output-dir test-results \
            --wait 10

      # Étape 9 : Déployer les métadonnées sur la branche main si applicable
      - name: Deploy metadata to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          sf project deploy start \
            --manifest .temp/package/package.xml \
            --source-dir .temp/force-app \
            --target-org cdcidev \
            --ignore-conflicts \
            --wait 10 \
            --verbose
